# Site
title: Harman Singh Hira
subtitle: "Just another coder I guess..."
description: "Welcome to my personal blog where I share my thoughts on coding, technology, and life."
keywords: Harman Singh Hira, hsinghhira, hsinghhira.me, blog, personal blog, hexo, hexo theme minima
author: Harman Singh Hira
language: en
timezone: "Auckland, New Zealand"
url: http://me.hsinghhira.me/
root: /
permalink: :title/
permalink_defaults:
pretty_urls:
  trailing_index: true
  trailing_html: true

source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ""
filename_case: 0
render_drafts: false
post_asset_folder: true
relative_link: false
future: true

highlight: false
prismjs: false
syntax_highlighter: "shiki"

shiki:
  themes:
    dark: "github-dark"
    light: "github-light"

index_generator:
  path: ""
  per_page: 10
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

meta_generator: true

date_format: YYYY-MM-DD
time_format: HH:mm:ss
updated_option: "mtime"

per_page: 10
pagination_dir: page

include:
exclude:
ignore:

all_minifier: true
html_minifier: true
css_minifier: true
js_minifier: true

theme: minima

deploy:
  type: git
  repo: https://github.com/HSinghHira/Its-Me.git
  branch: page
  message: "Last Update: {{ now('MM-DD HH:mm:ss') }}"
  cname: me.hsinghhira.me

lazyload:
  enable: true
  onlypost: false
  loadingImg: # /images/loading.gif
  isSPA: false
  preloadRatio: 3

feed:
  limit: 20
  order_by: "-date"
  tag_dir: "tag"
  category_dir: "category"
  rss:
    enable: true
    output: "rss.xml"
  atom:
    enable: true
    output: "atom.xml"
  jsonFeed:
    enable: true
    output: "feed.json"

seo:
  html:
    enable: true
    fix: true
    exclude:
      - "*.min.{htm,html}"
  css:
    enable: true
    exclude:
      - "**/*.min.css"
  js:
    enable: true
    concat: false
    exclude:
      - "**/*.min.js"
    options:
      compress:
        dead_code: true
      mangle:
        toplevel: true
        safari10: true
  schema:
    article:
      enable: true
    breadcrumb:
      enable: true
    sitelink:
      enable: true
    homepage:
      enable: true
  img:
    enable: true
    broken: false
    default: https://upload.wikimedia.org/wikipedia/commons/6/65/No-Image-Placeholder.svg
    onerror: serverside
  links:
    enable: true
    exclude:
      - hsinghhira.me
  sitemap:
    yoast: true
    gnews: true
  search:
    type: ["page", "post"]
  feed:
    type: [page, post]
    icon: "https://w7.pngwing.com/pngs/745/306/png-transparent-gallery-image-images-photo-picture-pictures-set-app-incredibles-icon-thumbnail.png"

generator_amp:
  templateDir: amp-template
  assetDistDir: amp-dist

hexo_external_link:
  enable: true
  enable_base64_encode: true
  url_param_name: "u"
  html_file_name: "go.html"
  target_blank: true
  link_rel: "external nofollow noopener noreferrer"
  domain: "me.hsinghhira.me"
  safety_chain: true
  ignore_attrs:
    - "data-fancybox"
    - "ignore-external-link"

robots:
  user_agent: "*"
  allow:
    - /
    - /archives/
    - /page/
    - /tags/
  disallow:
    - /js/
    - /css/
    - /images/
  sitemaps:
    - https://me.hsinghhira.me/sitemap.xml
    - https://me.hsinghhira.me/atom.xml
    - https://me.hsinghhira.me/rss.xml
    - https://me.hsinghhira.me/feed.json

cdn:
  server: https://images.weserv.nl
  use_webp: true
  native: false # use cloudflare native image resize
  max_width:
  exclude_domains:

analytics:
  google_analytics:
    enable: true
    measurement_id: G-GJF7D1TVGG
  microsoft_clarity:
    enable: true
    project_id: skvnh9ncl9
